// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5YNsQpBzFkAJo25wWbygOIToTievojvU',
    appId: '1:185939681304:web:1371cd1abc0abd76e7236d',
    messagingSenderId: '185939681304',
    projectId: 'healthchecker-4d7f9',
    authDomain: 'healthchecker-4d7f9.firebaseapp.com',
    storageBucket: 'healthchecker-4d7f9.appspot.com',
    measurementId: 'G-K9N7VZWBC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnIwjMxntu6CUfUmRa7V8Rjzjywsvlozk',
    appId: '1:185939681304:android:207fc2b999e118eee7236d',
    messagingSenderId: '185939681304',
    projectId: 'healthchecker-4d7f9',
    storageBucket: 'healthchecker-4d7f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPbvdCAALlbF9cB37p757meelhhsaW47o',
    appId: '1:185939681304:ios:b93624b0bcff9dcbe7236d',
    messagingSenderId: '185939681304',
    projectId: 'healthchecker-4d7f9',
    storageBucket: 'healthchecker-4d7f9.appspot.com',
    iosBundleId: 'com.example.healthcheckerbyheypion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPbvdCAALlbF9cB37p757meelhhsaW47o',
    appId: '1:185939681304:ios:be2f3e4e1d14bbfde7236d',
    messagingSenderId: '185939681304',
    projectId: 'healthchecker-4d7f9',
    storageBucket: 'healthchecker-4d7f9.appspot.com',
    iosBundleId: 'com.example.healthcheckerbyheypion.RunnerTests',
  );
}
